Repository textlint-ja/textlint-rule-preset-JTF-style, pull requests merged in 2024-12, with the labels that each got.

#127 かっこ と スペースに関するルールの修正とオプションの追加
  README.md
  src/3.3.js
  src/4.3.1.js
  test/3.3-test.js
  test/4.3.1-test.js
  test/fixtures/input.md
  test/fixtures/output.md
  tool/create-fixtures.js
Labels: Type: Feature, Type: Breaking Change

#134 chore!: Require Node.js 18+
  example/yarn.lock
  package.json
  test/fixer-test.js
  test/index-test.js
  yarn.lock
Labels: Type: Breaking Change

#140 README: JTFスタイルガイドとCCライセンスの素敵な関係のURL修正
  README.md
Labels: Type: Documentation

#144 CI: add Node.js 22
  .github/workflows/test.yml
  package.json
Labels: Type: CI
